title: Ali Morshid | Software Engineer
email: alimorsh@buffalo.edu
description: >- # this means to ignore newlines until "url:"
  Personal website of an aspiring software engineer.
url: "https://alimorshid.site"
baseurl: ""
twitter_username: aliofye
github_username:  aliofye
resume: https://docs.google.com/document/d/1eHqHSC6qZx8mHQCzfY2F-kwUuQlxYL5ShL7OXlrt4eQ/edit?usp=sharing

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed