title: Ali Morshid | Software Engineer
status: internship
graduation_date: Fall 2018
email: aliofye@gmail.com
description: >- # this means to ignore newlines until "url:"
  Personal website of an aspiring software engineer.
url: "https://ali.ooo"
baseurl: ""
favicon: "/img/favicon.ico"
twitter_username: aliofye
github_username:  aliofye
resume:
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-minifier
